sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
branches:
  only:
    - master
before_install:
  - npm i -g npm
before_script:
  - npm prune
script:
  - npm run test:ci
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release